[package]
name = "ahma_common"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
coverage = []

[dependencies]
anyhow.workspace = true
dirs.workspace = true
dunce.workspace = true
rcgen = "0.13.2"
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = [
    "sync",
    "net",
    "time",
    "io-util",
    "process",
] }
toml.workspace = true
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "ahma_coverage"
path = "src/bin/ahma_coverage.rs"
required-features = ["coverage"]

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["sync", "time", "rt", "macros", "test-util"] }
