use anyhow::Result;
use std::path::Path;
use std::sync::RwLock;

use super::core::Sandbox;
use super::types::SandboxMode;

/// Operator-configured passthrough allowlist (`[sandbox] env_allow`): variable
/// names preserved in tool subprocess environments despite matching a secret
/// pattern. Set once at startup from the loaded settings; empty by default so
/// the safe posture (scrub everything secret-looking) holds even when nothing
/// is configured. Process-global because it is a single operator policy, not
/// per-session state.
static SECRET_ENV_ALLOW: RwLock<Vec<String>> = RwLock::new(Vec::new());

/// Install the passthrough allowlist from `[sandbox] env_allow`. Called once at
/// startup. Names are stored as-is; matching is case-insensitive.
pub fn set_secret_env_allow(allow: Vec<String>) {
    if let Ok(mut guard) = SECRET_ENV_ALLOW.write() {
        *guard = allow;
    }
}

/// Return `true` if `name` looks like it holds a secret and should be scrubbed
/// from tool subprocess environments.
///
/// Uses unambiguous substring markers plus a `_`-delimited `TOKEN` segment
/// check, so genuine credentials (`ANTHROPIC_API_KEY`, `AWS_SECRET_ACCESS_KEY`,
/// `GITHUB_TOKEN`) match while non-secret look-alikes (`TOKENIZERS_PARALLELISM`)
/// do not.
///
/// Two credential-bearing names carry no marker at all and are matched by name:
/// `KUBECONFIG` (points at a file of cluster credentials) and `DATABASE_URL`
/// (embeds user:password in the URL). `DATABASE_URL` is a substring marker so
/// the common `TEST_DATABASE_URL` / `POSTGRES_DATABASE_URL` spellings match too.
///
/// This is deliberately *separate* from [`is_code_injection_env_name`]: the
/// reason differs (secrecy vs. arbitrary code execution) and so does the
/// matching (heuristic substrings vs. exact names).
pub fn is_secret_env_name(name: &str) -> bool {
    let upper = name.to_ascii_uppercase();
    const MARKERS: [&str; 9] = [
        "API_KEY",
        "APIKEY",
        "ACCESS_KEY",
        "SECRET",
        "PASSWORD",
        "PASSWD",
        "PASSPHRASE",
        "CREDENTIAL",
        // Credentials embedded in a connection URL — no other marker matches.
        "DATABASE_URL",
    ];
    if MARKERS.iter().any(|m| upper.contains(m)) {
        return true;
    }
    // Path to a file full of cluster credentials; the name carries no marker.
    if upper == "KUBECONFIG" {
        return true;
    }
    if upper.contains("PRIVATE") && upper.contains("KEY") {
        return true;
    }
    // `TOKEN` only as a whole `_`-delimited segment, so `TOKENIZERS_PARALLELISM`
    // (a non-secret ML flag) is not swept up but `GITHUB_TOKEN` is.
    upper.split('_').any(|seg| seg == "TOKEN")
}

/// Environment variables that make an *otherwise ordinary* command execute code
/// of the attacker's choosing, or delegate execution to somewhere the sandbox
/// does not reach (SPEC R-HANDOFF.5 categories 1 and 2; the client-redirect case
/// is R-HANDOFF.6). SPEC specifies the two categories and leaves the membership
/// here — this list is the data. Matched on the **exact** name
/// (case-insensitively), because unlike the secret heuristics these are specific,
/// documented mechanisms rather than a naming pattern.
///
/// Why this exists at all: ahma inherits its own environment wholesale, and a
/// poisoned launcher environment is a published escape — the 2026 Pillar
/// Security write-up chained an `Info.plist` `LSEnvironment` entry setting
/// `BASH_ENV=/tmp/payload.sh` into code execution outside the sandbox. Ahma runs
/// user commands as `bash -c "<cmd>"` (see [`Sandbox::create_shell_command`]),
/// and non-interactive bash still honours `BASH_ENV`, so the exact same primitive
/// applies here.
///
/// Entries and their mechanisms:
///
/// *Shell startup / behaviour*
/// - `BASH_ENV` — bash sources this file before running a non-interactive `-c`
///   command. Direct code execution on every single tool call.
/// - `ENV` — the POSIX equivalent, sourced by ksh/dash and by bash in POSIX
///   mode. (Accepted false-positive risk: some apps use `ENV=production`; that
///   is what `[sandbox] env_allow` is for.)
/// - `SHELLOPTS` / `BASHOPTS` — bash imports `set`/`shopt` options from the
///   environment at startup. `SHELLOPTS=posix` re-enables the `ENV` path,
///   `expand_aliases` changes what a command word means, `xtrace` echoes every
///   expanded command (including secrets) to stderr.
/// - `PS4` — the xtrace prompt is *expanded*, so `PS4='$(payload)'` executes
///   once tracing is on. Inert on its own; stripped as the companion to
///   `SHELLOPTS`.
/// - `BASH_FUNC_*` (prefix) — exported shell functions (`export -f`) are
///   inherited by `bash -c` and shadow real commands, so an inherited
///   `BASH_FUNC_git%%` redefines `git` for the whole session. This is the one
///   prefix rule in an otherwise exact-match list; the name is generated by
///   bash and has no legitimate inbound use here.
///
/// *Dynamic linker*
/// - `LD_PRELOAD` / `LD_AUDIT` — load an attacker library into *every*
///   dynamically linked child before `main`.
/// - `LD_LIBRARY_PATH` — searched ahead of the default directories, so it can
///   shadow `libc.so.6` itself; equivalent in power to `LD_PRELOAD`. This one
///   *is* legitimately set by conda/CUDA/ROS-style toolchains — it is stripped
///   by default because `env_allow` makes that recoverable, whereas a
///   not-stripped variable is not recoverable without a code change.
/// - `DYLD_INSERT_LIBRARIES` — macOS `LD_PRELOAD`.
/// - `DYLD_LIBRARY_PATH`, `DYLD_FRAMEWORK_PATH`,
///   `DYLD_FALLBACK_LIBRARY_PATH`, `DYLD_FALLBACK_FRAMEWORK_PATH` — macOS
///   library shadowing. The `FALLBACK_` pair must be listed too, or stripping
///   the first two is bypassed by using the fallback spelling. (dyld already
///   purges `DYLD_*` when exec'ing SIP-protected binaries such as
///   `/usr/bin/sandbox-exec`, so on the macOS Strict path this mostly makes an
///   existing guarantee explicit — but Test mode and non-macOS have no such
///   purge.)
///
/// *Language runtimes*
/// - `NODE_OPTIONS` — accepts `--require`/`--import`, i.e. run this file first.
/// - `PYTHONHOME` — repoints the interpreter at an attacker stdlib, executed at
///   startup.
/// - `PYTHONSTARTUP` — sourced by the interpreter (interactive only, hence weak,
///   but there is no legitimate inbound use).
/// - `PERL5OPT` — accepts `-M<module>`; `RUBYOPT` — accepts `-r<file>`.
/// - `JAVA_TOOL_OPTIONS`, `_JAVA_OPTIONS`, `JDK_JAVA_OPTIONS` — every JVM reads
///   them and they accept `-javaagent:/path/evil.jar`.
///
/// *Git and helper-command hooks* (git runs each of these as a command)
/// - `GIT_SSH_COMMAND`, `GIT_SSH`, `GIT_PROXY_COMMAND`, `GIT_EXTERNAL_DIFF`,
///   `GIT_PAGER`, `PAGER`, `GIT_EDITOR`, `EDITOR`, `VISUAL`, `GIT_ASKPASS`,
///   `SSH_ASKPASS` — each names a program git or ssh will execute. Stripping the
///   editor/pager names costs nothing here: child stdin is `/dev/null` and stdout
///   is a pipe, so nothing interactive can run anyway.
/// - `GIT_CONFIG_COUNT`, `GIT_CONFIG_GLOBAL`, `GIT_CONFIG_SYSTEM`, `GIT_CONFIG` —
///   inject arbitrary git config, which reaches `core.pager`, `core.fsmonitor`,
///   `core.sshCommand`, `diff.external` and `alias.*`. Dropping `GIT_CONFIG_COUNT`
///   neutralises the whole numbered `GIT_CONFIG_KEY_n`/`GIT_CONFIG_VALUE_n`
///   family, which git ignores without the count.
/// - `GIT_TEMPLATE_DIR` — `git init` copies hooks out of it.
///
/// *Execution delegated outside the sandbox*
/// - `DOCKER_HOST` / `DOCKER_CONTEXT` — point the client at a *remote* daemon.
///   Denying the local `docker.sock` at the filesystem layer (privileged
///   container + host bind mount = the daemon writes outside the scope on the
///   agent's behalf) is trivially sidestepped otherwise, and neither name
///   matches any secret marker.
///
/// **`SSH_AUTH_SOCK` is deliberately NOT here.** It is a considered exception,
/// not an oversight: it is a capability handle (the agent can sign with keys it
/// cannot read), but git-over-ssh is core to this workflow, and silently
/// breaking `git push` is exactly the kind of surprise this project refuses to
/// ship. Confining agent forwarding belongs to the ssh-agent, not to a strip
/// list. Likewise **`PYTHONPATH` / `RUBYLIB` / `PERL5LIB` / `NODE_PATH` are not
/// stripped**: they are module search paths that real build and test invocations
/// (`PYTHONPATH=src pytest`, tox, monorepo layouts) set as a matter of course,
/// and ahma synthesises Python workers, so stripping them would break the common
/// case far more often than it blocks the rare one.
pub fn is_code_injection_env_name(name: &str) -> bool {
    let upper = name.to_ascii_uppercase();
    // Exported bash functions: the only prefix family here (see doc comment).
    if upper.starts_with("BASH_FUNC_") {
        return true;
    }
    const NAMES: [&str; 39] = [
        // Shell startup / behaviour
        "BASH_ENV",
        "ENV",
        "SHELLOPTS",
        "BASHOPTS",
        "PS4",
        // Dynamic linker
        "LD_PRELOAD",
        "LD_AUDIT",
        "LD_LIBRARY_PATH",
        "DYLD_INSERT_LIBRARIES",
        "DYLD_LIBRARY_PATH",
        "DYLD_FRAMEWORK_PATH",
        "DYLD_FALLBACK_LIBRARY_PATH",
        "DYLD_FALLBACK_FRAMEWORK_PATH",
        // Language runtimes
        "NODE_OPTIONS",
        "PYTHONHOME",
        "PYTHONSTARTUP",
        "PERL5OPT",
        "RUBYOPT",
        "JAVA_TOOL_OPTIONS",
        "_JAVA_OPTIONS",
        "JDK_JAVA_OPTIONS",
        // Git / helper-command hooks
        "GIT_SSH_COMMAND",
        "GIT_SSH",
        "GIT_PROXY_COMMAND",
        "GIT_EXTERNAL_DIFF",
        "GIT_PAGER",
        "PAGER",
        "GIT_EDITOR",
        "EDITOR",
        "VISUAL",
        "GIT_ASKPASS",
        "SSH_ASKPASS",
        "GIT_CONFIG",
        "GIT_CONFIG_COUNT",
        "GIT_CONFIG_GLOBAL",
        "GIT_CONFIG_SYSTEM",
        "GIT_TEMPLATE_DIR",
        // Execution delegated outside the sandbox
        "DOCKER_HOST",
        "DOCKER_CONTEXT",
    ];
    NAMES.contains(&upper.as_str())
}

/// Every reason to strip a variable from a tool subprocess environment, in one
/// predicate: it looks like a credential ([`is_secret_env_name`]) *or* it makes
/// the child execute code the caller did not ask for
/// ([`is_code_injection_env_name`]). The two lists stay separate because their
/// rationale and matching differ; only the strip decision composes them.
pub fn is_stripped_env_name(name: &str) -> bool {
    is_secret_env_name(name) || is_code_injection_env_name(name)
}

/// Given an iterator of environment variable names and an allowlist, return the
/// names that must be scrubbed: matching [`is_stripped_env_name`] and not
/// allow-listed (case-insensitive exact match). Pure — the unit of behaviour
/// under test. The operator's `[sandbox] env_allow` applies uniformly to both
/// strip lists, so someone who genuinely needs `NODE_OPTIONS` or
/// `LD_LIBRARY_PATH` can allow it exactly as they would a token.
pub fn secret_env_keys<I>(names: I, allow: &[String]) -> Vec<String>
where
    I: IntoIterator<Item = String>,
{
    let allow_upper: Vec<String> = allow.iter().map(|a| a.to_ascii_uppercase()).collect();
    names
        .into_iter()
        .filter(|n| is_stripped_env_name(n) && !allow_upper.contains(&n.to_ascii_uppercase()))
        .collect()
}

/// Remove secret-bearing and code-injecting environment variables from `cmd`,
/// honoring the operator `[sandbox] env_allow` passthrough list. Every place that
/// spawns a tool subprocess must call this: the kernel sandbox restricts the
/// filesystem, not environment inheritance, so a child would otherwise inherit
/// the server's `ANTHROPIC_API_KEY`, `AWS_*`, etc. and could dump them via `env`
/// — or inherit a poisoned `BASH_ENV`/`LD_PRELOAD` and run attacker code on
/// every tool call.
pub fn scrub_secret_env(cmd: &mut tokio::process::Command, context: &str) {
    let allow = SECRET_ENV_ALLOW
        .read()
        .map(|g| g.clone())
        .unwrap_or_default();
    let scrubbed = secret_env_keys(std::env::vars().map(|(k, _)| k), &allow);
    if !scrubbed.is_empty() {
        tracing::debug!(
            "Scrubbed {} secret-bearing or code-injecting env var(s) from {context}: {:?}",
            scrubbed.len(),
            scrubbed
        );
        for key in &scrubbed {
            cmd.env_remove(key);
        }
    }
}

/// The `HTTP_PROXY`/`HTTPS_PROXY`/`NO_PROXY` variables that route every sandboxed
/// subprocess through the local guarded egress proxy (`--restrict-network`,
/// R-NET). Empty unless the operator turned restriction on; set once at startup
/// after the proxy binds its port. Process-global for the same reason as
/// [`SECRET_ENV_ALLOW`]: it is a single operator policy, and it must reach every
/// spawn site — `base_command` *and* the shell pool — none of which share a
/// `Sandbox` handle.
static EGRESS_PROXY_ENV: RwLock<Vec<(String, String)>> = RwLock::new(Vec::new());

/// Install the egress-proxy environment (from a started [`super::super::egress::EgressProxy`]).
/// Called once at server startup when `--restrict-network` is on. Passing an empty
/// vec (the default) leaves subprocess egress unrestricted.
pub fn set_egress_proxy_env(vars: Vec<(String, String)>) {
    if let Ok(mut guard) = EGRESS_PROXY_ENV.write() {
        *guard = vars;
    }
}

/// Inject the egress-proxy variables into `cmd`. A no-op when restriction is off.
/// Applied *after* [`scrub_secret_env`] at every subprocess spawn site so a tool
/// that honours `HTTP_PROXY` reaches the network only through the allow-listed,
/// SSRF-guarded proxy. (A tool that ignores the proxy variables is not contained
/// by this alone — see the network-restriction limitations in the README.)
pub fn apply_egress_proxy_env(cmd: &mut tokio::process::Command) {
    let vars = EGRESS_PROXY_ENV
        .read()
        .map(|g| g.clone())
        .unwrap_or_default();
    apply_proxy_vars(cmd, &vars);
}

/// Pure core of [`apply_egress_proxy_env`]: set `vars` on `cmd` (a no-op when
/// empty). Split out so the injection is unit-testable without the process-global.
fn apply_proxy_vars(cmd: &mut tokio::process::Command, vars: &[(String, String)]) {
    if !vars.is_empty() {
        cmd.envs(vars.iter().cloned());
    }
}

impl Sandbox {
    /// Create a sandboxed tokio process Command.
    pub fn create_command(
        &self,
        program: &str,
        args: &[String],
        working_dir: &Path,
    ) -> Result<tokio::process::Command> {
        if self.mode == SandboxMode::Test {
            return Ok(self.base_command(program, args, working_dir));
        }

        self.create_platform_sandboxed_command(program, args, working_dir)
    }

    pub(super) fn base_command(
        &self,
        program: &str,
        args: &[String],
        working_dir: &Path,
    ) -> tokio::process::Command {
        let mut cmd = tokio::process::Command::new(program);
        cmd.args(args)
            .current_dir(working_dir)
            .kill_on_drop(true)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped());

        // Scrub ahma's internal supervision markers so they never leak into the
        // commands ahma runs. Without this, a tool/user command (or a test) that
        // itself launches `ahma serve` would inherit a bogus server-child role and
        // spawn depth, making the nested server skip its bridge or trip the
        // spawn-depth backstop. These vars are set deliberately only on intentional
        // `ahma serve` children (spawn_background_bridge / SubprocessPeerFactory).
        cmd.env_remove("AHMA_SERVER_CHILD")
            .env_remove(ahma_common::process_guard::SPAWN_DEPTH_ENV)
            .env_remove("AHMA_RESTARTED");

        // Scrub secret-bearing environment variables so a sandboxed (or
        // prompt-injected) tool cannot read the server's credentials out of its
        // own process environment and exfiltrate them. The kernel sandbox
        // restricts the filesystem, not environment inheritance — `env`,
        // `printenv`, and `/proc/self/environ` all read process memory the
        // sandbox cannot gate. The same call also drops the code-injection
        // variables (`BASH_ENV`, `LD_PRELOAD`, `NODE_OPTIONS`, …), which turn a
        // poisoned *launcher* environment into arbitrary code in every child ahma
        // spawns. Names on the operator's `[sandbox] env_allow` list are
        // preserved for tools that legitimately need one.
        scrub_secret_env(&mut cmd, program);

        // Route the subprocess through the guarded egress proxy when
        // `--restrict-network` is on (a no-op otherwise). After the scrub so the
        // proxy vars are never mistaken for secrets.
        apply_egress_proxy_env(&mut cmd);

        // Run each command as its own process-group leader so the whole tree can
        // be killed as a unit on timeout/cancellation. On macOS the direct child
        // is `sandbox-exec`, which execs `sh -c "<cmd>"`, which may fan out to
        // `cargo` → `rustc` → `cc`; signalling only the direct child (what
        // `kill_on_drop`/`Child::kill` do) orphans those descendants, leaking
        // build processes until they finish. With a dedicated group the adapter
        // can `kill(-pgid)` the entire subtree (see `kill_process_tree`).
        #[cfg(unix)]
        cmd.process_group(0);

        cmd
    }

    fn create_platform_sandboxed_command(
        &self,
        program: &str,
        args: &[String],
        working_dir: &Path,
    ) -> Result<tokio::process::Command> {
        #[cfg(target_os = "linux")]
        {
            // Landlock restricts only the calling thread, so the process-level
            // enforcement at startup does not cover children spawned from tokio
            // worker threads. Restrict each child at spawn time instead: build a
            // ruleset fd from the current scopes and apply it between fork and
            // exec, where the child is still single-threaded.
            let mut cmd = self.base_command(program, args, working_dir);
            if let Some(fd) = self.spawn_landlock_ruleset_fd()? {
                use std::os::fd::AsRawFd;
                // SAFETY: the closure only performs async-signal-safe syscalls
                // (prctl + landlock_restrict_self); the OwnedFd moved into it
                // stays open across fork so the raw fd remains valid in the child.
                unsafe {
                    cmd.pre_exec(move || {
                        super::landlock::apply_landlock_ruleset_in_child(fd.as_raw_fd())
                    });
                }
            }
            Ok(cmd)
        }

        #[cfg(target_os = "macos")]
        {
            // On macOS, wrap each command with sandbox-exec
            let mut full_command = vec![program.to_string()];
            full_command.extend(args.iter().cloned());

            let (sandbox_program, sandbox_args) =
                self.build_macos_sandbox_command(&full_command, working_dir)?;

            Ok(self.base_command(&sandbox_program, &sandbox_args, working_dir))
        }

        #[cfg(not(any(target_os = "linux", target_os = "macos")))]
        {
            // Windows: every command is launched into an AppContainer whose SID
            // has been granted exactly the locked scopes (R6.3.3), on top of the
            // Job Object process-tree containment applied at startup (R6.3.2).
            //
            // The plan is turned into a command via `base_command` rather than
            // built here, so the Windows path picks up the secret and
            // code-injection env scrub, the egress-proxy variables and
            // `kill_on_drop` that Linux and macOS already get. The previous
            // Windows arm built its own `std::process::Command` and had none of
            // them — a tool subprocess on Windows inherited ahma's credentials.
            #[cfg(target_os = "windows")]
            {
                let write_scopes = self.scopes().to_vec();
                let plan = super::windows::plan_windows_sandboxed_spawn(
                    program,
                    args,
                    &write_scopes,
                    &self.read_scopes(),
                )?;
                let launcher = plan.launcher.to_string_lossy().into_owned();
                let mut cmd = self.base_command(&launcher, &plan.args, working_dir);
                cmd.envs(plan.env);
                return Ok(cmd);
            }
            // Other non-Linux/macOS platforms (e.g., FreeBSD): run unsandboxed.
            #[cfg(not(target_os = "windows"))]
            Ok(self.base_command(program, args, working_dir))
        }
    }

    /// Build a Landlock ruleset fd from the sandbox's *current* scopes for
    /// restricting one child process at spawn time (via `pre_exec`).
    ///
    /// Returns `Ok(None)` in Test mode, and on kernels without Landlock
    /// support — strict-mode servers already fail closed at startup via
    /// `check_sandbox_prerequisites`, so `None` here only occurs for
    /// in-process embedders, which fall back to application-level path checks.
    #[cfg(target_os = "linux")]
    pub fn spawn_landlock_ruleset_fd(&self) -> Result<Option<std::os::fd::OwnedFd>> {
        if self.mode == SandboxMode::Test {
            return Ok(None);
        }
        let scopes = self.scopes().to_vec();
        // R-NET: when the guarded egress proxy is active, confine the child's
        // outbound TCP to the proxy port (Landlock ≥ 6.7). `None` leaves network
        // unrestricted (restriction off / advisory tier).
        let connect_tcp_port = self
            .egress_proxy_addr
            .read()
            .ok()
            .and_then(|g| *g)
            .map(|addr| addr.port());
        let fd = super::landlock::landlock_ruleset_fd(
            &scopes,
            &self.read_scopes(),
            self.is_no_temp_files(),
            self.package_cache_write(),
            connect_tcp_port,
        )?;
        if fd.is_none() {
            tracing::warn!(
                "Landlock unavailable on this kernel — child process spawned without \
                 kernel-level restrictions (application-level path checks still apply)"
            );
        }
        Ok(fd)
    }

    /// Create a sandboxed shell command (e.g. `bash -c "..."` on Unix,
    /// `powershell -NoProfile -NonInteractive -Command "..."` on Windows).
    pub fn create_shell_command(
        &self,
        shell_program: &str,
        full_command: &str,
        working_dir: &Path,
    ) -> Result<tokio::process::Command> {
        #[cfg(target_os = "windows")]
        let args = vec![
            "-NoProfile".to_string(),
            "-NonInteractive".to_string(),
            "-Command".to_string(),
            full_command.to_string(),
        ];
        #[cfg(not(target_os = "windows"))]
        let args = vec!["-c".to_string(), full_command.to_string()];
        self.create_command(shell_program, &args, working_dir)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn apply_proxy_vars_injects_and_empty_is_noop() {
        // Empty vars → no env is set on the command.
        let mut cmd = tokio::process::Command::new("true");
        apply_proxy_vars(&mut cmd, &[]);
        assert_eq!(
            cmd.as_std().get_envs().count(),
            0,
            "empty proxy vars must not touch the command environment"
        );

        // Non-empty vars → each is set explicitly on the command.
        let vars = vec![
            ("HTTP_PROXY".to_string(), "http://127.0.0.1:9".to_string()),
            (
                "NO_PROXY".to_string(),
                "127.0.0.1,::1,localhost".to_string(),
            ),
        ];
        let mut cmd = tokio::process::Command::new("true");
        apply_proxy_vars(&mut cmd, &vars);
        let set: std::collections::HashMap<_, _> = cmd
            .as_std()
            .get_envs()
            .map(|(k, v)| {
                (
                    k.to_string_lossy().into_owned(),
                    v.map(|v| v.to_string_lossy().into_owned()),
                )
            })
            .collect();
        assert_eq!(
            set.get("HTTP_PROXY").and_then(|v| v.as_deref()),
            Some("http://127.0.0.1:9")
        );
        assert_eq!(
            set.get("NO_PROXY").and_then(|v| v.as_deref()),
            Some("127.0.0.1,::1,localhost")
        );
    }

    fn make_test_sandbox(scope: &std::path::Path) -> Sandbox {
        Sandbox::new(
            vec![scope.to_path_buf()],
            SandboxMode::Test,
            false,
            false,
            false,
        )
        .unwrap()
    }

    #[test]
    fn secret_env_names_match_real_credentials() {
        for name in [
            "ANTHROPIC_API_KEY",
            "OPENAI_API_KEY",
            "AWS_SECRET_ACCESS_KEY",
            "AWS_ACCESS_KEY_ID",
            "AWS_SESSION_TOKEN",
            "GITHUB_TOKEN",
            "GH_TOKEN",
            "MY_SECRET",
            "DB_PASSWORD",
            "SIGNING_PASSPHRASE",
            "GCP_CREDENTIALS",
            "SSH_PRIVATE_KEY",
            "apikey",
        ] {
            assert!(
                is_secret_env_name(name),
                "{name} should be treated as secret"
            );
        }
    }

    /// Credential-bearing names that carry none of the substring markers.
    #[test]
    fn kubeconfig_and_database_url_are_secret() {
        for name in [
            "KUBECONFIG",
            "kubeconfig",
            "DATABASE_URL",
            "TEST_DATABASE_URL",
            "POSTGRES_DATABASE_URL",
        ] {
            assert!(
                is_secret_env_name(name),
                "{name} embeds credentials and must be scrubbed"
            );
        }
    }

    /// Every name on the code-injection list is stripped, and the strip decision
    /// composes the two lists.
    #[test]
    fn code_injection_env_names_are_stripped() {
        for name in [
            "BASH_ENV",
            "ENV",
            "SHELLOPTS",
            "BASHOPTS",
            "PS4",
            "BASH_FUNC_git%%", // exported shell function, shadows a real command
            "LD_PRELOAD",
            "LD_AUDIT",
            "LD_LIBRARY_PATH",
            "DYLD_INSERT_LIBRARIES",
            "DYLD_LIBRARY_PATH",
            "DYLD_FRAMEWORK_PATH",
            "DYLD_FALLBACK_LIBRARY_PATH",
            "DYLD_FALLBACK_FRAMEWORK_PATH",
            "NODE_OPTIONS",
            "PYTHONHOME",
            "PYTHONSTARTUP",
            "PERL5OPT",
            "RUBYOPT",
            "JAVA_TOOL_OPTIONS",
            "_JAVA_OPTIONS",
            "JDK_JAVA_OPTIONS",
            "GIT_SSH_COMMAND",
            "GIT_SSH",
            "GIT_PROXY_COMMAND",
            "GIT_EXTERNAL_DIFF",
            "GIT_PAGER",
            "PAGER",
            "GIT_EDITOR",
            "EDITOR",
            "VISUAL",
            "GIT_ASKPASS",
            "SSH_ASKPASS",
            "GIT_CONFIG",
            "GIT_CONFIG_COUNT",
            "GIT_CONFIG_GLOBAL",
            "GIT_CONFIG_SYSTEM",
            "GIT_TEMPLATE_DIR",
            "DOCKER_HOST",
            "DOCKER_CONTEXT",
            "bash_env", // matching is case-insensitive
        ] {
            assert!(
                is_code_injection_env_name(name),
                "{name} executes attacker-chosen code and must be stripped"
            );
            assert!(
                is_stripped_env_name(name),
                "{name} must be stripped via the composed predicate too"
            );
        }
    }

    /// The two lists compose: a name on either one is stripped, a name on
    /// neither survives, and neither list swallows the other's members.
    #[test]
    fn secret_and_code_injection_lists_compose() {
        // Secret-only.
        assert!(is_secret_env_name("GITHUB_TOKEN"));
        assert!(!is_code_injection_env_name("GITHUB_TOKEN"));
        // Code-injection-only.
        assert!(is_code_injection_env_name("BASH_ENV"));
        assert!(!is_secret_env_name("BASH_ENV"));
        // Neither.
        assert!(!is_stripped_env_name("PATH"));

        let scrubbed = secret_env_keys(
            vec![
                "GITHUB_TOKEN".to_string(),
                "BASH_ENV".to_string(),
                "DOCKER_HOST".to_string(),
                "KUBECONFIG".to_string(),
                "PATH".to_string(),
                "SSH_AUTH_SOCK".to_string(),
            ],
            &[],
        );
        assert_eq!(
            scrubbed,
            vec![
                "GITHUB_TOKEN".to_string(),
                "BASH_ENV".to_string(),
                "DOCKER_HOST".to_string(),
                "KUBECONFIG".to_string(),
            ],
            "both lists must contribute, and nothing else"
        );
    }

    /// `SSH_AUTH_SOCK` survives on purpose: git-over-ssh is core to the workflow
    /// (see the `is_code_injection_env_name` doc comment). If this test fails
    /// someone added it to a strip list — that is a product decision, not a typo.
    #[test]
    fn ssh_auth_sock_survives_the_scrub() {
        assert!(!is_secret_env_name("SSH_AUTH_SOCK"));
        assert!(!is_code_injection_env_name("SSH_AUTH_SOCK"));
        assert!(!is_stripped_env_name("SSH_AUTH_SOCK"));
        assert!(
            secret_env_keys(vec!["SSH_AUTH_SOCK".to_string()], &[]).is_empty(),
            "SSH_AUTH_SOCK must reach tool subprocesses so `git push` keeps working"
        );
    }

    /// The operator escape hatch applies uniformly to the code-injection list,
    /// not just to secrets.
    #[test]
    fn env_allow_overrides_a_code_injection_strip() {
        let names = vec![
            "NODE_OPTIONS".to_string(),
            "LD_LIBRARY_PATH".to_string(),
            "BASH_ENV".to_string(),
            "ANTHROPIC_API_KEY".to_string(),
        ];
        // Lowercase in config to prove case-insensitive matching.
        let allow = vec!["node_options".to_string(), "LD_library_PATH".to_string()];
        let scrubbed = secret_env_keys(names, &allow);
        assert!(
            !scrubbed.contains(&"NODE_OPTIONS".to_string()),
            "allow-listed code-injection var must survive"
        );
        assert!(
            !scrubbed.contains(&"LD_LIBRARY_PATH".to_string()),
            "allow-listed code-injection var must survive"
        );
        assert!(
            scrubbed.contains(&"BASH_ENV".to_string()),
            "a code-injection var that is not allow-listed must still be stripped"
        );
        assert!(
            scrubbed.contains(&"ANTHROPIC_API_KEY".to_string()),
            "allowing a code-injection var must not weaken the secret scrub"
        );
    }

    /// Names that merely resemble a strip-list entry must survive: the
    /// code-injection list is exact-match, unlike the secret heuristics.
    #[test]
    fn code_injection_matching_is_exact() {
        for name in [
            "ENVIRONMENT",      // not `ENV`
            "NODE_ENV",         // not `ENV`
            "APP_ENV",          // not `ENV`
            "PAGERDUTY_URL",    // not `PAGER`
            "EDITOR_THEME",     // not `EDITOR`
            "MY_DOCKER_HOST",   // not `DOCKER_HOST`
            "PYTHONPATH",       // deliberately not stripped (module search path)
            "NODE_PATH",        // ditto
            "PERL5LIB",         // ditto
            "RUBYLIB",          // ditto
            "LD_LIBRARY_PATHS", // not `LD_LIBRARY_PATH`
            "BASH_FUNCTION",    // not the `BASH_FUNC_` prefix
        ] {
            assert!(
                !is_code_injection_env_name(name),
                "{name} must not be swept up by the exact-match list"
            );
        }
    }

    #[test]
    fn benign_env_names_are_not_secret() {
        for name in [
            "PATH",
            "HOME",
            "LANG",
            "CARGO_HOME",
            "RUSTUP_TOOLCHAIN",
            "TOKENIZERS_PARALLELISM", // contains "TOKEN" but not as a segment
            "KEYBOARD_LAYOUT",
            "ACCESSIBILITY",
        ] {
            assert!(
                !is_secret_env_name(name),
                "{name} should not be treated as secret"
            );
            assert!(
                !is_stripped_env_name(name),
                "{name} should reach tool subprocesses untouched"
            );
        }
    }

    #[test]
    fn secret_env_keys_respects_allowlist_case_insensitively() {
        let names = vec![
            "ANTHROPIC_API_KEY".to_string(),
            "GITHUB_TOKEN".to_string(),
            "PATH".to_string(),
        ];
        // Allow GITHUB_TOKEN through (lowercase in config to prove case-insensitivity).
        let allow = vec!["github_token".to_string()];
        let scrubbed = secret_env_keys(names, &allow);
        assert!(scrubbed.contains(&"ANTHROPIC_API_KEY".to_string()));
        assert!(
            !scrubbed.contains(&"GITHUB_TOKEN".to_string()),
            "allow-listed var must survive"
        );
        assert!(
            !scrubbed.contains(&"PATH".to_string()),
            "non-secret var must survive"
        );
    }

    /// A tool subprocess must not inherit a secret-looking env var.
    #[test]
    fn base_command_scrubs_secret_env_from_child() {
        // SAFETY: single-threaded test; sets/removes a uniquely-named var.
        unsafe {
            std::env::set_var("AHMA_TEST_FAKE_API_KEY", "sk-should-be-scrubbed");
            std::env::set_var("AHMA_TEST_PLAIN_VAR", "keepme");
        }
        let td = tempdir().unwrap();
        let sandbox = make_test_sandbox(td.path());
        let cmd = sandbox.base_command("env", &[], td.path());
        let child_env: std::collections::HashMap<String, String> = cmd
            .as_std()
            .get_envs()
            .filter_map(|(k, v)| {
                // Only keys with an explicit override appear here; a scrubbed key
                // shows up as (key, None).
                Some((
                    k.to_string_lossy().into_owned(),
                    v?.to_string_lossy().into_owned(),
                ))
            })
            .collect();
        // The scrubbed key must be explicitly removed (present as a removal).
        let removed: Vec<String> = cmd
            .as_std()
            .get_envs()
            .filter(|(_, v)| v.is_none())
            .map(|(k, _)| k.to_string_lossy().into_owned())
            .collect();
        assert!(
            removed.contains(&"AHMA_TEST_FAKE_API_KEY".to_string()),
            "secret var must be scrubbed (removed) from child env; removed={removed:?}"
        );
        assert!(
            !child_env.contains_key("AHMA_TEST_PLAIN_VAR"),
            "non-secret var is inherited normally (not explicitly overridden)"
        );
        unsafe {
            std::env::remove_var("AHMA_TEST_FAKE_API_KEY");
            std::env::remove_var("AHMA_TEST_PLAIN_VAR");
        }
    }

    /// A tool subprocess must not inherit a code-injection env var from a
    /// poisoned launcher environment. Uses `PYTHONSTARTUP` rather than
    /// `BASH_ENV`/`LD_PRELOAD` so setting it in the test process cannot itself
    /// perturb any shell or linker this suite invokes.
    #[test]
    fn base_command_scrubs_code_injection_env_from_child() {
        // SAFETY: nextest runs each test in its own process; the var is removed
        // again below and names a path that no test interpreter reads.
        unsafe {
            std::env::set_var("PYTHONSTARTUP", "payload.py");
        }
        let td = tempdir().unwrap();
        let sandbox = make_test_sandbox(td.path());
        let cmd = sandbox.base_command("env", &[], td.path());
        let removed: Vec<String> = cmd
            .as_std()
            .get_envs()
            .filter(|(_, v)| v.is_none())
            .map(|(k, _)| k.to_string_lossy().into_owned())
            .collect();
        assert!(
            removed.contains(&"PYTHONSTARTUP".to_string()),
            "code-injection var must be scrubbed from child env; removed={removed:?}"
        );
        assert!(
            !removed.contains(&"SSH_AUTH_SOCK".to_string()),
            "SSH_AUTH_SOCK must never be scrubbed; removed={removed:?}"
        );
        unsafe {
            std::env::remove_var("PYTHONSTARTUP");
        }
    }

    /// create_command in Test mode delegates directly to base_command.
    #[test]
    fn test_create_command_test_mode_succeeds() {
        let td = tempdir().unwrap();
        let sandbox = make_test_sandbox(td.path());
        let result = sandbox.create_command("echo", &["hello".to_string()], td.path());
        assert!(result.is_ok(), "create_command in Test mode should succeed");
    }

    /// create_shell_command in Test mode produces a valid command.
    #[test]
    fn test_create_shell_command_test_mode_succeeds() {
        let td = tempdir().unwrap();
        let sandbox = make_test_sandbox(td.path());

        // Use platform-appropriate shell
        #[cfg(not(target_os = "windows"))]
        let shell = "sh";
        #[cfg(target_os = "windows")]
        let shell = "powershell";

        let result = sandbox.create_shell_command(shell, "echo hello", td.path());
        assert!(
            result.is_ok(),
            "create_shell_command in Test mode should succeed"
        );
    }

    /// create_command in Strict mode on this platform should also succeed
    /// (on macOS wraps with sandbox-exec, on Linux runs directly via Landlock).
    #[test]
    fn test_create_command_strict_mode_succeeds() {
        let td = tempdir().unwrap();
        let sandbox = Sandbox::new(
            vec![td.path().to_path_buf()],
            SandboxMode::Strict,
            false,
            false,
            false,
        )
        .unwrap();
        let result = sandbox.create_command("echo", &["hi".to_string()], td.path());
        assert!(
            result.is_ok(),
            "create_command in Strict mode should succeed: {result:?}"
        );
    }
}
