use ahma_simplify::analysis::{ScanOptions, perform_analysis};
use std::fs;
use tempfile::TempDir;

#[test]
fn test_pipeline_skips_gitignored_build_caches_and_generated_code() {
    let temp = TempDir::new().unwrap();
    let root = temp.path();

    // 1. Legitimate source files that SHOULD be analyzed
    let src_dir = root.join("src");
    fs::create_dir_all(&src_dir).unwrap();
    fs::write(
        src_dir.join("main.rs"),
        r#"pub fn calculate_total(prices: &[f64]) -> f64 {
    let mut sum = 0.0;
    for p in prices {
        if *p > 0.0 {
            sum += *p;
        }
    }
    sum
}
"#,
    )
    .unwrap();

    // 2. Gitignore file and gitignored directory/file
    fs::write(root.join(".gitignore"), "gitignored_dir/\nlocal_cache.rs\n").unwrap();
    let gitignored_dir = root.join("gitignored_dir");
    fs::create_dir_all(&gitignored_dir).unwrap();
    fs::write(
        gitignored_dir.join("secret.rs"),
        "pub fn ignored() { panic!(); }",
    )
    .unwrap();
    fs::write(root.join("local_cache.rs"), "pub fn cache() { panic!(); }").unwrap();

    // 3. Build caches (Gradle, Gradle cache, node_modules, target, etc.)
    let gradle_cache = root.join("gradle_cache");
    fs::create_dir_all(&gradle_cache).unwrap();
    fs::write(
        gradle_cache.join("Transformed.kt"),
        "class Transformed { fun run() {} }",
    )
    .unwrap();

    let gradle_user_home = root.join("android/polar/.gradle_user_home/caches");
    fs::create_dir_all(&gradle_user_home).unwrap();
    fs::write(
        gradle_user_home.join("Artifact.kt"),
        "class Artifact { fun cache() {} }",
    )
    .unwrap();

    let node_modules = root.join("node_modules/pkg");
    fs::create_dir_all(&node_modules).unwrap();
    fs::write(node_modules.join("index.js"), "module.exports = {};").unwrap();

    // 4. Generated UniFFI C header and Kotlin bindings (both pattern and content banner)
    let ios_dir = root.join("ios");
    fs::create_dir_all(&ios_dir).unwrap();
    fs::write(
        ios_dir.join("stat3FFI.h"),
        "/* Generated by uniffi. DO NOT EDIT. */\nvoid stat3_init(void);",
    )
    .unwrap();

    let android_core = root.join("android/core/src/main/java/fi/neubit/stat3");
    fs::create_dir_all(&android_core).unwrap();
    fs::write(
        android_core.join("stat3.kt"),
        r#"// This file was autogenerated by uniffi
// DO NOT EDIT
package fi.neubit.stat3

class Stat3 {
    fun run() {}
}
"#,
    )
    .unwrap();

    // 5. Protobuf generated file
    let proto_dir = root.join("proto");
    fs::create_dir_all(&proto_dir).unwrap();
    fs::write(
        proto_dir.join("service.pb.rs"),
        "// Generated by prost-build\npub struct Service;",
    )
    .unwrap();

    // 6. Generated Go file with Go codegen banner
    let go_dir = root.join("pkg/api");
    fs::create_dir_all(&go_dir).unwrap();
    fs::write(
        go_dir.join("client.go"),
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
    )
    .unwrap();

    // 7. Migrations and testdata directories
    let migrations = root.join("db/migrations");
    fs::create_dir_all(&migrations).unwrap();
    fs::write(
        migrations.join("001_create_users.sql"),
        "CREATE TABLE users (id INT PRIMARY KEY);",
    )
    .unwrap();

    let testdata = root.join("testdata");
    fs::create_dir_all(&testdata).unwrap();
    fs::write(
        testdata.join("sample.rs"),
        "pub fn sample_data() -> &'static str { \"test\" }",
    )
    .unwrap();

    // 8. Custom excluded file via flag
    let custom_dir = root.join("custom_skip");
    fs::create_dir_all(&custom_dir).unwrap();
    fs::write(custom_dir.join("manual.rs"), "pub fn manual_skip() {}").unwrap();

    let output_dir = temp.path().join("output");
    fs::create_dir_all(&output_dir).unwrap();

    let extensions = vec![
        "rs".to_string(),
        "kt".to_string(),
        "js".to_string(),
        "go".to_string(),
        "h".to_string(),
    ];
    let custom_excludes = vec!["/custom_skip/".to_string()];

    let scan = perform_analysis(
        root,
        &output_dir,
        false,
        &ScanOptions {
            extensions: &extensions,
            excludes: &custom_excludes,
            changed: None,
            compute_metrics: true,
        },
        None,
    )
    .unwrap();

    let analyzed_paths: Vec<String> = scan
        .sources
        .iter()
        .map(|(p, _)| {
            p.strip_prefix(root)
                .unwrap_or(p)
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();

    // The ONLY file that should have been analyzed is src/main.rs!
    assert_eq!(
        analyzed_paths,
        vec!["src/main.rs".to_string()],
        "Expected only src/main.rs to be analyzed, but got: {:?}",
        analyzed_paths
    );
}

#[test]
fn test_custom_excludes_various_pattern_formats() {
    let temp = TempDir::new().unwrap();
    let root = temp.path();

    let files = [
        "src/keep.rs",
        "src/specific.kt",
        "pkg/sub/relative.rs",
        "my_gen/gen.rs",
        "my_gen2/gen2.rs",
        "src/file.custom",
        "src/MyCodeGenService.rs",
    ];

    for file_path in files {
        let full = root.join(file_path);
        fs::create_dir_all(full.parent().unwrap()).unwrap();
        fs::write(&full, "pub fn test() {}").unwrap();
    }

    let output_dir = temp.path().join("output");
    fs::create_dir_all(&output_dir).unwrap();

    let extensions = vec!["rs".to_string(), "kt".to_string(), "custom".to_string()];
    let custom_excludes = vec![
        "specific.kt".to_string(),
        "pkg/sub/relative.rs".to_string(),
        "/my_gen/".to_string(),
        "my_gen2/".to_string(),
        "*.custom".to_string(),
        "*CodeGen*".to_string(),
    ];

    let scan = perform_analysis(
        root,
        &output_dir,
        false,
        &ScanOptions {
            extensions: &extensions,
            excludes: &custom_excludes,
            changed: None,
            compute_metrics: true,
        },
        None,
    )
    .unwrap();

    let analyzed_paths: Vec<String> = scan
        .sources
        .iter()
        .map(|(p, _)| {
            p.strip_prefix(root)
                .unwrap_or(p)
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();

    assert_eq!(
        analyzed_paths,
        vec!["src/keep.rs".to_string()],
        "Expected only src/keep.rs to be kept, but got: {:?}",
        analyzed_paths
    );
}

#[test]
fn test_minified_and_snapshot_files_are_excluded() {
    let temp = TempDir::new().unwrap();
    let root = temp.path();

    let files = [
        "src/app.js",
        "static/app.min.js",
        "static/style.min.css",
        "dist/bundle.js",
        "tests/test.snap",
        "tests/corpus.golden",
    ];

    for file_path in files {
        let full = root.join(file_path);
        fs::create_dir_all(full.parent().unwrap()).unwrap();
        fs::write(&full, "function x() {}").unwrap();
    }

    let output_dir = temp.path().join("output");
    fs::create_dir_all(&output_dir).unwrap();

    let extensions = vec![
        "js".to_string(),
        "css".to_string(),
        "snap".to_string(),
        "golden".to_string(),
    ];

    let scan = perform_analysis(
        root,
        &output_dir,
        false,
        &ScanOptions {
            extensions: &extensions,
            excludes: &[],
            changed: None,
            compute_metrics: true,
        },
        None,
    )
    .unwrap();

    let analyzed_paths: Vec<String> = scan
        .sources
        .iter()
        .map(|(p, _)| {
            p.strip_prefix(root)
                .unwrap_or(p)
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();

    assert_eq!(
        analyzed_paths,
        vec!["src/app.js".to_string()],
        "Expected only src/app.js to be analyzed, but got: {:?}",
        analyzed_paths
    );
}
